### ISSUE TITLE
the texts is off-centered, just a tab

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/modularity-mindfulness#3]
Either the image or the one p tag are missing/ needs some sort of padding or margin. I'm not sure which or how much, this is the last thing I need for this screenshot to match and then I can work on the larger sizes. 

@hellachella
@JessJodoin

**Comment by JessJodoin** [comment]
Could you show me what your talking about?

**Comment by NikCasar** [comment]
<img width="327" alt="image" src="https://user-images.githubusercontent.com/55094132/95084167-8007ad00-06eb-11eb-9aef-7f7d08e532c1.png">

@hellachella
@JessJodoin

**Comment by hellachella** [comment]
It looks to me like you have a bit too much padding on the body. It's squishing your image in,

**Comment by JessJodoin** [comment]
Hey 😄 Was this issue resolved? If so, could you close this issue?
